import type { NextPage } from 'next';
import Head from 'next/head';
import { GetServerSideProps } from 'next';
import { getToken } from 'next-auth/jwt';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">
          <h1 className="text-4xl font-bold">Welcome to CampusLife!</h1>
        </div>
      </main>
    </>
  );
};

export default Home;

// getserversideprops
export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  const token = await getToken({ req, secret: process.env.SECRET });
  console.log(token);
  if (!token) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    };
  }

  if (token.role === 'admin') {
    return {
      redirect: {
        destination: '/admin',
        permanent: false,
      },
    };
  } else if (token.role === 'student') {
    return {
      redirect: {
        destination: '/student',
        permanent: false,
      },
    };
  } else if (token.role === 'teacher') {
    return {
      redirect: {
        destination: '/teacher',
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
};
